# Generated by Django 5.0.3 on 2024-03-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='number',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
