# Generated by Django 5.0.3 on 2024-03-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_batch_updated_at_alter_number_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='opt_in_status',
            field=models.BooleanField(null=True),
        ),
    ]
