# Generated by Django 5.0.3 on 2024-03-18 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatepage',
            old_name='template_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='templatepage',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='templates.template'),
        ),
    ]
