# Generated by Django 5.0.3 on 2024-03-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_rename_template_type_templatepage_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templateoption',
            old_name='option_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='templateoption',
            old_name='option_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='templateoption',
            old_name='option_value',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='bearer_token',
        ),
        migrations.AddField(
            model_name='template',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='templateoption',
            name='description',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='templatepage',
            name='menu_title',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='templatepage',
            name='footer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='templatepage',
            name='header',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
