# Generated by Django 5.0.3 on 2024-03-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_rename_option_text_templateoption_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatepage',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
