# Generated by Django 5.0.3 on 2024-03-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_templatepage_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatepage',
            name='body',
            field=models.CharField(max_length=500),
        ),
    ]
