# Generated by Django 5.0.3 on 2024-03-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0006_alter_templateoption_template_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateoption',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='templateoption',
            name='text',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='templateoption',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
